### ISSUE TITLE
Conrrection in UI

### ISSUE THREAD

**Issue by luisplata** [luisplata/PACO#21]
![image](https://user-images.githubusercontent.com/9086926/115334013-3b5fd280-a160-11eb-8835-a4480b371bce.png)
Atender detalle de lo expuesto en imagen

**Comment by ErizOPP** [comment]
Si en alguna no se entendio algo de lo explicado ahi avisame por privado de discord o nose si tenes mi numero que al toque te respondo

**Comment by luisplata** [comment]
Para este issue, si es un poco complicado medir al milimetro, pero hice lo que pude.
Es posible que tengamos varias iteraciones sobre este punto, de momento, solucionado.
