### ISSUE TITLE
Bug Pictionary

### ISSUE THREAD

**Issue by ErizOPP** [luisplata/PACO#22]
La pizarra se estira dependiendo del largo del celular, abria que conseguir que siempre se quede fija el tamaño

Ademas cuando le doy a jugar suponete que a proposito le doy con el dedo 3 o 4 veces para ver que pasa se pone medio loco

- Algunas veces se repite 3 veces el Ready Go

- Otras veces veo como que en vez de tirar la palabra para dibujar de la nada dice que tenes que tomar x0 cervezas 

Luego si se pudiera poner el recuadro ese negro si se puede te paso un png de que podria quedar piola y sino un simple recuadro en vez de negro que sea blanco pero con la transparencia nose en 60% o 80%

![1618885781756](https://user-images.githubusercontent.com/82858055/115333901-d2348b00-a170-11eb-86e0-624fb15e046e.jpg)

**Comment by luisplata** [comment]
Se mantiene el ratio del tamaño de la pizarra y se mantiene anclado a la parte izquierda de la pantalla.
