### ISSUE TITLE
APP Responsive: Pantalla inicio

### ISSUE THREAD

**Issue by ErizOPP** [luisplata/PACO#24]
Dividir la pantalla en 3 areas distintas

TOPNAV: Solo contenga el título del juego para que éste independientemente de la pantalla se coloque lo mas arriba posible (dejas espacio en píxeles en vacío así no está tan arriba el título)

MAIN: Solo van los distintos juegos con su respectivo botón e icono. Este área ocupa lo sobrante de los otros dos en el medio. Si hay tantos juegos que no ocupa en la pantalla se puede aplicar un scroll vertical.

FOOTER: Solo van las respectivas configuraciones, sonido, redes demás juegos, créditos y copyright.

**Comment by luisplata** [comment]
Se realiza la respectiva división entre los elementos de la pantalla inicial.
